### ISSUE TITLE
1.14.0 giving gradle error: Found data binding errors

### ISSUE THREAD

**Issue by Benjoyo** [algolia/instantsearch-android#105] opened 2018-11-27 10:41 UTC
I cloned the example repo [instantsearch-android-mvp](https://github.com/algolia/instantsearch-android-mvp) which builds and runs fine but uses instantsearch 1.12.0.
If I change the version to 1.14.0 and as a result also change imports in _MainActivity_ to _com.algolia.instantsearch.core.helpers.Searcher_ and _com.algolia.instantsearch.ui.helpers.InstantSearch_ i get the following build error:

```
FAILURE: Build failed with an exception.

 * What went wrong:
 Execution failed for task ':app:compileDebugJavaWithJavac'.
 > android.databinding.tool.util.LoggedErrorException: Found data binding errors.
   ****/ data binding error ****msg:Cannot find the setter for attribute 'algolia:attribute' with parameter  type java.lang.String on android.widget.ImageView.
   file:C:\Users\Bennet\git\instantsearch-android-mvp-master\app\src\main\res\layout\hits_item.xml
   loc:18:33 - 18:39
   ****\ data binding error ****


 * Try:
 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log  output. Run with --scan to get full insights.

 * Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

The same is true when I try to use the barebones example in a project of mine, there gradle additionally stated that _HitsItemBindingImpl_ doesn't exist, hence the binding error.

**Comment by PLNech** [comment] 2018-11-27 15:21
Hi @Benjoyo, thanks for your report! 

I was able to reproduce your setup [upgrading the MVP to 1.14.0](https://github.com/algolia/instantsearch-android-mvp/commit/9045a8301da3d1b5fdd44294944024d610442d45). This seems due to an issue between the Gradle plugin and `android.databinding`, which is resolved by [updating the gradle plugin to 3.3.x](https://github.com/algolia/instantsearch-android-mvp/commit/0bfa2f25e5f891febc2323b4424e28322be15699) (which also means updating the Gradle Wrapper to `4.10.1`).

I suspect the root cause was an **erroneous databinding expression** in [`hits_item.xml`](https://github.com/algolia/instantsearch-android-mvp/blob/9045a8301da3d1b5fdd44294944024d610442d45/app/src/main/res/layout/hits_item.xml#L31), which is simply ignored with the new versions. 
Regardless, I [fixed the expression](https://github.com/algolia/instantsearch-android-mvp/commit/875b582569a5513c636f6ce88aa31c3f7b6b21ac?diff=unified) to have the expected impact (use `colorAccent` to highlight product names).

As the problem is resolved, I'll close this issue for now - please reopen it if you still have the error with the latest MVP codebase or if you have further questions :)

**Closed by PLNech** 2018-11-27 15:21 UTC
