### ISSUE TITLE
Landing page - Small glitch on conclusion CTA

### ISSUE THREAD

**Issue by sebnvzt** [algolia/instantsearch-android#24] opened 2017-03-28 09:09 UTC
In the end of the mobile version of Android IS LP, the conclusion CTA is cut. 

Bug seen on iPhone 7+, with Safari.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/23098634/24397576/f270130a-13a6-11e7-9826-4d6a5527a86b.jpg)

**Comment by LukyVj** [comment] 2017-03-28 14:55
Need more input, cannot reproduce

**Comment by LukyVj** [comment] 2017-03-28 14:59
Ok, there is definitely a problem on mobile resizing

**Comment by LukyVj** [comment] 2017-03-28 15:48
The fix is in his way

**Comment by PLNech** [comment] 2017-05-05 14:52
@sebnvzt I cannot reproduce the issue, is it still happening for you? And if yes, what screen size?

@LukyVj did you push the fix? If yes I'll close this issue 🙂

**Closed** 2017-05-12 09:03 UTC
Labels: bug, documentation
