### ISSUE TITLE
Too much work on main thread when using Custom Hit Views

### ISSUE THREAD

**Issue by janakaj** [algolia/instantsearch-android#36] opened 2017-05-04 06:30 UTC
I get the following warning (and noticeable screen stuttering) when using a Custom Hit views.

`Skipped 51 frames!  The application may be doing too much work on its main thread.`

The entire layout has one `ImageView` and three `TextViews`. For the text views, I have followed the example in [_TimestampHitView_](https://github.com/algolia/instantsearch-android-examples/blob/master/media/src/main/java/com/algolia/instantsearch/examples/media/views/TimestampHitView.java), because I need some simple formatting before I set the text.

Note: If I directly use `algolia:attribute` I don't have this issue, but then I can't format my text.

Any ideas on what I might be doing wrong?

FYI: I am using a real device, not an emulator.

**Comment by PLNech** [comment] 2017-05-05 08:03
Hi @janakaj, thank you for reporting this issue! 

Can you share the code of your `onUpdateView` method? It will help me reproduce your situation.

**Comment by janakaj** [comment] 2017-05-05 12:08
@PLNech The code is below.

    @Override
    public void onUpdateView(JSONObject result) {
        double priceDouble = result.optDouble("price");
        setText(new DecimalFormat("$#").format(priceDouble / 100d));
    }

Upon further investigation, I found that this only happens on the first query (after initialization etc.). Subsequent queries are fine. Here's my initialization code (this is in a fragment).

    Client client = new Client(ALGOLIA_APP_ID, ALGOLIA_SEARCH_API_KEY);
    index = client.getIndex(ALGOLIA_INDEX_NAME);
    searcher = new Searcher(index);
    InstantSearchHelper helper = new InstantSearchHelper(hits, searcher);
    helper.registerSearchView(getActivity(), searchBox);
    updateSearchQuery();

`updateSearchQuery()` basically sets some query parameters and calls `searcher.search()`.

Like I said subsequent calls to `updateSearchQuery()` doesn't result in skipping frames.

**Comment by PLNech** [comment] 2017-05-05 13:28
@janakaj thanks for all these details! 
I'm investigating what could cause this, I'll keep you informed of my progress :)

**Comment by PLNech** [comment] 2017-05-05 14:38
@janakaj : I only was able to partially reproduce your issue: if I increase the time needed by `onUpdateView` to complete, I'm getting skipped frames but for every request, not simply the first one. Actually it's not even at every request, rather at every instantiation of such an `AlgoliaHitView`. Which makes sense as this code is run on the UI thread, so any consequent computation in `onUpdateView` could cause skipped frames.

It seems `DecimalFormat.format()` [has some performance limitations](http://stackoverflow.com/questions/8553672/a-faster-alternative-to-decimalformat-format), this could explain your situation.
Could you try wrapping your code in an AsyncTask, executing `new DecimalFormat("$#").format(priceDouble / 100d));` in **`doInBackground`** and `setText` in *`onProgressUpdate`*? This will execute data transformation in a background thread and only update the View in the main thread, which in my case fixed these skipped frames.

Here's how `TimestampHitView.onUpdateView()` looks like with such an `AsyncTask`:

```
@Override
    public void onUpdateView(final JSONObject result) {
        new AsyncTask<JSONObject, String, Void>() {

            @Override protected Void doInBackground(JSONObject... params) {
                String timestamp = result.optString("published");
                Log.e("PLN", "Timestamp:" + timestamp + "(" + this.toString() + ")");
                try {
                    Thread.sleep(1000);
                    String text = new PrettyTime().format(new Date(Long.parseLong(timestamp) * 1000));
                    Log.e("PLN", "Text:" + text + "(" + this.toString() + ")");
                    publishProgress(text);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                return null;
            }

            @Override protected void onProgressUpdate(String... values) {
                setText(values[0]);
                Log.e("PLN", "setText (" + this.toString() + ")");
            }
        }.execute();

    }
```

**Comment by janakaj** [comment] 2017-05-06 03:07
@PLNech Thanks for the response and the code example, but I doubt this is the issue, because even if I do absolutely nothing in `onUpdateView` I still have the same problem.

In fact, upon further investigation, I found that even when I use `algolia:attribute` I still have the same issue. Below is my entire layout.


    <?xml version="1.0" encoding="utf-8"?>
    <layout>
    
        <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            xmlns:tools="http://schemas.android.com/tools"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="16dp">
    
            <ImageView
                android:id="@+id/coverImage"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                app:layout_constraintHorizontal_bias="0.507"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:srcCompat="@drawable/placeholder_cover_image" />
    
            <TextView
                android:id="@+id/price"
                style="@style/AppTheme.Body1Bold"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/coverImage"
                app:attribute='@{"objectID"}'
                tools:text="$2000" />
    
            <TextView
                android:id="@+id/mainCaption"
                style="@style/AppTheme.Body1"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginEnd="8dp"
                android:layout_marginRight="8dp"
                app:attribute='@{"objectID"}'
                app:layout_constraintBaseline_toBaselineOf="@+id/price"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toRightOf="parent"
                tools:text="This is the main caption" />
    
            <TextView
                android:id="@+id/secondCaption"
                style="@style/AppTheme.Body2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:attribute='@{"objectID"}'
                android:layout_marginTop="4dp"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/mainCaption"
                tools:text="This is the second caption" />
    
            <LinearLayout
                android:id="@+id/verified_badge"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="12dp"
                android:background="@color/brandAccent"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingBottom="8dp"
                android:paddingLeft="12dp"
                android:paddingRight="12dp"
                android:paddingTop="8dp"
                android:visibility="invisible"
                app:layout_constraintLeft_toLeftOf="@+id/coverImage"
                app:layout_constraintTop_toTopOf="@+id/coverImage">
    
                <ImageView
                    android:layout_width="18dp"
                    android:layout_height="18dp"
                    android:adjustViewBounds="true"
                    android:tint="@android:color/white"
                    app:srcCompat="@drawable/ic_verified_user_black_24dp" />
    
                <TextView
                    style="@style/AppTheme.Body2"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:paddingLeft="8dp"
                    android:text="@string/ui_listing_verified"
                    android:textColor="@android:color/white"
                    tools:text="VERIFIED" />
            </LinearLayout>
    
    
        </android.support.constraint.ConstraintLayout>
    </layout>


Some observations:

+ If I remove the `coverImage` Image View, I don't have an issue.
+ I thought theat maybe the issue was with `ConstraintLayout` so I built a similar layout with `RelativeLayout` as the parent, but I still had the same issue.

**Comment by PLNech** [comment] 2017-05-09 12:58
@janakaj thanks for your answer, indeed from this new information our situation seems unrelated to the Custom hit view mechanism. 

I'm surprised by the fact that removing `coverImage` stops the issue from happening, as apart from inflating this layout InstantSearch should not interact with that View. This would mean there is a general problem when inflating `ImageViews` in hit layouts, which I was unable to confirm for now.

- Does the issue persist when you replace `coverImage` by another `ImageView` that is not referenced by any other View of the layout? If yes, does it disappear when that ImageView has no `src[Compat]` attribute set? (this would narrow down the problem in the bitmap loading)


I'm having a hard time reproducing your issue, as running our example apps (both having an `ImageView` in their `hits_item` layouts) either on a real phone or in an emulator did not result in skipped frames.
- What device are you testing this on?
- Do you also see skipped frames on this device when running our example apps?

Also, do you still see these skipped frames only on first search? If you are using the Hits' `loadMore` mechanism, do you see again skipped frames when scrolling through the pages?

**Comment by janakaj** [comment] 2017-05-11 12:20
@PLNech thanks for the response and I do apologise haven't been able to do more testing on this issue. I will report back here as soon as possible.

FYI: The device I am using is a OnePlus 1 (first generation), I realise this could be the issue as well. I will try to get my hands on a couple of other devices as well and get back to you.

**Comment by PLNech** [comment] 2017-05-12 08:23
@janakaj no problem! Thanks for this detail, I don't have a OnePlus 1 at hand but I'll check what happens on a few different phones.

I will be unavailable next week, but if you do more testing don't hesitate to share your findings here and I'll catch-up on Monday 22! 🙂

**Comment by PLNech** [comment] 2017-06-28 13:15
Hello @janakaj, how are you doing? 
It's been some time I didn't hear from you, do you still see this issue happening on your device?

**Comment by PLNech** [comment] 2017-07-17 09:23
Closed as we cannot reproduce the issue reported by @janakaj. 

_If you find yourself still affected by this issue, feel free to reopen it **with sample code demonstrating it**_.

**Closed by PLNech** 2017-07-17 09:23 UTC
Labels: cannot reproduce, performance
